# Site settings
title: RDIPD Blog    				  	#你博客的标题
SEOTitle: RDIPD | 禾文咨询    	 #显示在浏览器上搜索的时候显示的标题
# header-img: img/post-bg-rwd.jpg  	#显示在首页的背景图片
email: bhung@hewinsz.com	
description: "A blog for RD management"  			 #网站介绍
keyword: "IPD, RDIPD Blog, 禾文的博客" #关键词
url: "https://github.com/cnhewin/RDIPD"          # 这个就是填写你的博客地址
baseurl: "hewinsz.com"      # 这个我们不用填写

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "IPD产品经营管理"
sidebar-avatar:/img/hbregister.JPG      # 你的个人头像 这里你可以改成在img文件夹中的备用照片 img/avatar-m 或 avatar-g